repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/timothycrosley/isort
    rev: 5.5.4
    hooks:
      - id: isort
